# Generated by Django 4.0.2 on 2022-11-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_blog_editor_blog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
