# Generated by Django 4.0 on 2022-02-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
