# Generated by Django 4.0.2 on 2022-08-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='whatssap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
