# Generated by Django 4.0.2 on 2022-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0002_acount_whatssap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
