# Generated by Django 4.0.2 on 2022-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0004_alter_acount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
