# Generated by Django 4.0.2 on 2022-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0006_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='acount',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('AGENT', 'AGENT'), ('CUSTOMER', 'CUSTOMER')], default='CUSTOMER', max_length=10),
        ),
    ]
