# Generated by Django 4.0.2 on 2023-01-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0007_acount_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
