# Generated by Django 4.0.2 on 2023-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0008_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
