# Generated by Django 4.0.2 on 2022-06-20 16:27

import Main.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conatct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testomany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('review', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('num_rooms', models.IntegerField()),
                ('rent_type', models.CharField(blank=True, choices=[('سنة', 'سنة'), ('شهر', 'شهر'), ('أسبوع', 'أسبوع'), ('يوم', 'يوم')], max_length=10, null=True)),
                ('created', models.DateTimeField(verbose_name=datetime.timedelta(0))),
                ('space', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('cover', models.ImageField(upload_to=Main.models.uplaod_lucationn)),
                ('bathrooms', models.IntegerField()),
                ('Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('aria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='Main.aria')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.building')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='H_Mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Main.models.uplaod_lucation)),
                ('proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaage', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
