# Generated by Django 4.0 on 2022-02-18 20:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
