# Generated by Django 4.0 on 2022-02-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_house_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house')),
            ],
        ),
    ]
