# Generated by Django 4.0 on 2022-02-05 20:36

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Main.models.uplaod_video),
        ),
    ]
