# Generated by Django 4.0.2 on 2022-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rent_alter_house_rent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
