# Generated by Django 4.0 on 2022-02-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acounnt', '0001_initial'),
        ('Main', '0004_house_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agents', to='Acounnt.acount'),
        ),
    ]
