# Generated by Django 4.0 on 2022-02-06 10:18

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_house_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.uplaod_lucation),
        ),
    ]
