# Generated by Django 4.0.2 on 2022-09-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_favirte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favirte',
            name='propertys',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.house'),
        ),
    ]
