# Generated by Django 4.0.2 on 2022-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_favirte_propertys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favirte',
            name='propertys',
        ),
        migrations.AddField(
            model_name='favirte',
            name='propertys',
            field=models.ManyToManyField(to='Main.House'),
        ),
    ]
