# Generated by Django 4.0 on 2022-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_blog_blog_catagory_building_house_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(choices=[('للبيع', 'للبيع'), ('للأيجار', 'للأيجار')], max_length=10),
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='blog_catagory',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
