# Generated by Django 4.0.2 on 2022-09-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_favirte_propertys_favirte_propertys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favirte',
            name='propertys',
        ),
        migrations.AddField(
            model_name='favirte',
            name='propertys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.house'),
        ),
    ]
