# Generated by Django 4.0.2 on 2022-09-05 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0008_remove_favirte_propertys_favirte_propertys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favirte',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favirte',
            name='propertys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorties', to='Main.house'),
        ),
    ]
