# Generated by Django 4.0 on 2022-02-10 20:44

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_comment_post_alter_house_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='video',
        ),
        migrations.AlterField(
            model_name='house',
            name='cover',
            field=models.ImageField(upload_to=Main.models.uplaod_lucationn),
        ),
    ]
