# Generated by Django 4.0.2 on 2022-09-05 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0009_alter_favirte_customer_alter_favirte_propertys'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Favortie',
            field=models.ManyToManyField(related_name='favorties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favirte',
        ),
    ]
