# Generated by Django 4.0 on 2022-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_house_video_alter_house_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('messaage', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
