# Generated by Django 4.0.2 on 2022-09-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_house_favortie_delete_favirte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Favortie',
        ),
    ]
