# Generated by Django 4.0.2 on 2022-09-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0011_remove_house_favortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorties', to='Main.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
