# Generated by Django 4.0.2 on 2022-09-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_favorties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorties',
            old_name='lng',
            new_name='house',
        ),
    ]
