# Generated by Django 4.0.2 on 2022-09-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0013_rename_lng_favorties_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='favourties',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorties',
        ),
    ]
