# Generated by Django 4.0.2 on 2022-11-01 15:54

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_house_favourties_delete_favorties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.uplaod_lucationn),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
