# Generated by Django 4.0.2 on 2022-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_house_building_type_alter_house_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
