# Generated by Django 4.0.2 on 2022-11-04 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0017_alter_house_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
