# Generated by Django 4.0.2 on 2022-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_house_editor_house_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='conatct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
