# Generated by Django 4.0.2 on 2022-11-08 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_conatct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conatct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
