# Generated by Django 4.0.2 on 2022-11-18 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_conatct_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lati', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='H_Mapp',
        ),
        migrations.AddField(
            model_name='house',
            name='lucation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.mapp'),
        ),
    ]
