# Generated by Django 4.0.2 on 2022-11-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_mapp_delete_h_mapp_house_lucation'),
    ]

    operations = [
        migrations.CreateModel(
            name='H_Mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='lucation',
        ),
        migrations.DeleteModel(
            name='Mapp',
        ),
        migrations.AddField(
            model_name='h_mapp',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.house'),
        ),
    ]
