# Generated by Django 4.0.2 on 2022-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_h_mapp_remove_house_lucation_delete_mapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lati',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='H_Mapp',
        ),
    ]
